# Generated by Django 3.1.7 on 2021-08-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_auto_20210804_2017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_no', models.BigIntegerField(unique=True, verbose_name='编号')),
                ('task_name', models.CharField(max_length=100, verbose_name='名称')),
                ('task_detail', models.CharField(max_length=500, verbose_name='详情')),
                ('status', models.SmallIntegerField(choices=[(0, '已创建'), (1, '待分配'), (2, '待测试'), (3, '测试中'), (4, '已完成'), (5, '已关闭')], default=0, verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(0, '紧急'), (1, '重要'), (2, '一般'), (3, '普通')], verbose_name='优先级')),
                ('type', models.SmallIntegerField(choices=[(0, 'DEV任务'), (1, 'PUB任务'), (2, '生产任务'), (3, '回归任务'), (4, '冒烟任务')], verbose_name='类型')),
                ('prd_no', models.CharField(blank=True, max_length=80, null=True, verbose_name='关联需求编号')),
                ('expected_end_time', models.DateTimeField(verbose_name='预期完成时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('is_delay', models.BooleanField(default=False, verbose_name='延期')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'tp_job',
            },
        ),
        migrations.CreateModel(
            name='JobToCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_status', models.SmallIntegerField(choices=[(0, 'WAITING'), (1, 'PASS'), (2, 'FAIL'), (3, 'BLOCKED'), (4, 'BREAK')], verbose_name='用例状态')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='用例')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务用例关联表',
                'verbose_name_plural': '任务用例关联表',
                'db_table': 'tp_job_to_case',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='case',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobToCase', to='cases.Case', verbose_name='关联用例'),
        ),
        migrations.AddField(
            model_name='job',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='job',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
    ]
