# Generated by Django 3.1.7 on 2021-12-10 18:48

import backend.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_no', models.BigIntegerField(unique=True, verbose_name='编号')),
                ('task_name', models.CharField(db_index=True, max_length=100, verbose_name='名称')),
                ('task_detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='详情')),
                ('status', models.SmallIntegerField(choices=[(0, '已创建'), (1, '待指派'), (2, '待测试'), (3, '测试中'), (4, '已完成'), (5, '已挂起')], default=0, verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(0, '紧急'), (1, '重要'), (2, '一般'), (3, '普通')], verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='可用状态')),
                ('type', models.SmallIntegerField(choices=[(0, 'DEV任务'), (1, 'PUB任务'), (2, '生产任务'), (3, '回归任务'), (4, '冒烟任务')], verbose_name='类型')),
                ('product', models.CharField(blank=True, max_length=10, null=True, verbose_name='产品')),
                ('frontend', models.CharField(blank=True, max_length=20, null=True, verbose_name='前端')),
                ('backend', models.CharField(blank=True, max_length=20, null=True, verbose_name='后端')),
                ('prd_no', models.CharField(blank=True, max_length=80, null=True, verbose_name='关联需求编号')),
                ('expect_end_time', models.DateTimeField(verbose_name='预期完成时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('is_delay', models.BooleanField(default=False, verbose_name='延期')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'tp_job',
            },
        ),
        migrations.CreateModel(
            name='JobToCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_status', models.SmallIntegerField(choices=[(0, 'WAIT'), (1, 'PASS'), (2, 'FAIL'), (3, 'BLOCK'), (4, 'BREAK')], default=0, verbose_name='用例状态')),
                ('test_detail', models.CharField(blank=True, max_length=2000, null=True, verbose_name='测试结果详情')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='用例')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务用例关联表',
                'verbose_name_plural': '任务用例关联表',
                'db_table': 'tp_job_case',
            },
        ),
        migrations.CreateModel(
            name='JobRelateTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务测试关联表',
                'verbose_name_plural': '任务测试关联表',
                'db_table': 'tp_job_tester',
            },
        ),
    ]
