# Generated by Django 3.1.7 on 2021-12-10 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('cases', '0002_auto_20211210_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrelatetester',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='测试人员'),
        ),
        migrations.AddField(
            model_name='job',
            name='case',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobToCase', to='cases.Case', verbose_name='关联用例'),
        ),
        migrations.AddField(
            model_name='job',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='job',
            name='executor',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobRelateTester', to=settings.AUTH_USER_MODEL, verbose_name='测试人员'),
        ),
    ]
