# Generated by Django 3.1.7 on 2021-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='详情'),
        ),
    ]
