# Generated by Django 3.1.7 on 2021-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtocase',
            table='tp_job_case',
        ),
    ]
