# Generated by Django 3.1.7 on 2021-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210805_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtocase',
            name='case_status',
            field=models.SmallIntegerField(choices=[(0, 'WAITING'), (1, 'PASS'), (2, 'FAIL'), (3, 'BLOCKED'), (4, 'BREAK')], default=0, verbose_name='用例状态'),
        ),
    ]
