# Generated by Django 3.1.7 on 2021-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210805_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtocase',
            name='test_detail',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='测试结果详情'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已创建'), (1, '待指派'), (2, '待测试'), (3, '测试中'), (4, '已完成'), (5, '挂起')], default=0, verbose_name='状态'),
        ),
    ]
