# Generated by Django 3.1.7 on 2021-08-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='名称'),
        ),
    ]
