# Generated by Django 3.1.7 on 2021-08-29 23:17

import backend.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210829_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_time',
            field=backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='update_time',
            field=backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='jobtocase',
            name='create_time',
            field=backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobtocase',
            name='update_time',
            field=backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
