# Generated by Django 3.1.7 on 2021-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210808_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='expected_end_time',
            new_name='expect_end_time',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已创建'), (1, '待指派'), (2, '待测试'), (3, '测试中'), (4, '已完成'), (5, '已挂起')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='jobtocase',
            name='case_status',
            field=models.SmallIntegerField(choices=[(0, 'WAIT'), (1, 'PASS'), (2, 'FAIL'), (3, 'BLOCK'), (4, 'BREAK')], default=0, verbose_name='用例状态'),
        ),
    ]
