# Generated by Django 3.1.7 on 2021-09-02 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_auto_20210829_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='后端'),
        ),
        migrations.AddField(
            model_name='job',
            name='frontend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='前端'),
        ),
        migrations.AddField(
            model_name='job',
            name='product',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='job',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='测试人员'),
        ),
    ]
