# Generated by Django 3.1.7 on 2021-09-02 18:30

import backend.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20210902_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='executor',
        ),
        migrations.CreateModel(
            name='JobRelateTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='任务')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='测试人员')),
            ],
            options={
                'verbose_name': '任务测试关联表',
                'verbose_name_plural': '任务测试关联表',
                'db_table': 'tp_job_tester',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='executor',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobRelateTester', to=settings.AUTH_USER_MODEL, verbose_name='测试人员'),
        ),
    ]
