# Generated by Django 3.1.7 on 2021-12-10 18:48

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to='', verbose_name='文件地址')),
                ('name', models.CharField(max_length=20, verbose_name='文件名称')),
                ('scope', models.SmallIntegerField(choices=[(0, 'xmind_template')], unique=True, verbose_name='作用域')),
            ],
            options={
                'verbose_name': '系统文件',
                'verbose_name_plural': '系统文件',
                'db_table': 'tp_file',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='', verbose_name='图片地址')),
                ('scope', models.SmallIntegerField(choices=[(0, 'login'), (1, 'logo'), (2, 'auto_true'), (3, 'auto_false'), (4, 'loading')], unique=True, verbose_name='作用域')),
            ],
            options={
                'verbose_name': '系统图片',
                'verbose_name_plural': '系统图片',
                'db_table': 'tp_image',
            },
        ),
    ]
