# Generated by Django 3.1.7 on 2021-08-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='scope',
            field=models.SmallIntegerField(choices=[(0, 'login'), (1, 'home'), (2, 'case'), (3, 'job')], verbose_name='作用域'),
        ),
    ]
