# Generated by Django 3.1.7 on 2021-12-13 10:06

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.BigIntegerField(verbose_name='UID')),
                ('name', models.CharField(max_length=250, verbose_name='资源名称')),
                ('os', models.CharField(max_length=12, verbose_name='操作系统')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('size', models.CharField(max_length=10, verbose_name='文件大小')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_id', models.CharField(max_length=200, verbose_name='资源路径')),
                ('author', models.CharField(max_length=20, verbose_name='贡献者')),
            ],
            options={
                'verbose_name': '系统资源',
                'verbose_name_plural': '系统资源',
                'db_table': 'tp_source',
            },
        ),
    ]
