# Generated by Django 3.1.7 on 2021-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210804_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.SmallIntegerField(choices=[(3, 'other'), (2, 'background'), (1, 'icon')], default=3, verbose_name='图片类型'),
        ),
    ]
