# Generated by Django 3.1.7 on 2022-01-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_sourcemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcemodel',
            old_name='author',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='sourcemodel',
            name='file_id',
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='下载次数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='desc',
            field=models.CharField(default='', max_length=48, verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='资源名称'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='uid',
            field=models.BigIntegerField(unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='version',
            field=models.CharField(max_length=30, verbose_name='版本'),
        ),
        migrations.CreateModel(
            name='SourceStorePathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, unique=True, verbose_name='资源路径')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='files.sourcemodel', verbose_name='资源ID')),
            ],
        ),
    ]
