# Generated by Django 3.1.7 on 2022-01-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220105_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='desc',
            field=models.CharField(default='', max_length=48, verbose_name='简介'),
        ),
    ]
