# Generated by Django 3.1.7 on 2021-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210805_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'background'), (3, 'other'), (1, 'icon')], default=3, verbose_name='图片类型'),
        ),
    ]
