# Generated by Django 3.1.7 on 2021-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210805_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'icon'), (3, 'other'), (2, 'background')], default=3, verbose_name='图片类型'),
        ),
    ]
