# Generated by Django 3.1.7 on 2021-10-10 00:01

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20211009_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to='', verbose_name='文件地址')),
                ('scope', models.SmallIntegerField(choices=[(0, 'xmind_template')], verbose_name='作用域')),
            ],
            options={
                'verbose_name': '系统文件',
                'verbose_name_plural': '系统文件',
                'db_table': 'tp_file',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='图片地址'),
        ),
    ]
