# Generated by Django 3.1.7 on 2021-08-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_id', models.CharField(max_length=50, unique=True, verbose_name='用例编号')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('level', models.CharField(choices=[('H', '高'), ('M', '中'), ('L', '低')], default='M', max_length=1, verbose_name='用例等级')),
                ('owner', models.CharField(max_length=20, verbose_name='用例OWNER')),
                ('is_auto', models.BooleanField(default=False, verbose_name='自动化实现')),
                ('exec_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='执行路径')),
                ('step', models.CharField(blank=True, max_length=300, null=True, verbose_name='测试步骤')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='用例描述')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本号')),
                ('add_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='用例编写时间')),
                ('status', models.BooleanField(default=True, verbose_name='可用状态')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'tp_case',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uuid', models.CharField(max_length=36, verbose_name='UUID')),
                ('name', models.CharField(max_length=20, verbose_name='应用名称')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'db_table': 'tp_application',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uuid', models.CharField(max_length=36, verbose_name='UUID')),
                ('name', models.CharField(max_length=30, verbose_name='功能模块')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='cases.client', verbose_name='应用名称')),
            ],
            options={
                'verbose_name': '功能模块',
                'verbose_name_plural': '功能模块',
                'db_table': 'tp_module',
            },
        ),
    ]
