# Generated by Django 3.1.7 on 2021-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210804_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='应用名称'),
        ),
    ]
