# Generated by Django 3.1.7 on 2021-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20211210_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='1cb2b8c8e1799e2f6d56f58b1eabf38b', max_length=36, verbose_name='UUID'),
        ),
    ]
