# Generated by Django 3.1.7 on 2021-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20211212_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='7b0cd1ce1002a7120b10bb007ec16467', max_length=36, verbose_name='UUID'),
        ),
    ]
