# Generated by Django 3.1.7 on 2021-08-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210819_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='bda2c13d31fd3032aac2547bd1b6b64b', max_length=36, verbose_name='UUID'),
        ),
    ]
