# Generated by Django 3.1.7 on 2021-08-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20210828_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='ed7b6d7b10a149e582ac78f441aa43f5', max_length=36, verbose_name='UUID'),
        ),
    ]
