# Generated by Django 3.1.7 on 2021-08-29 23:17

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20210829_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='module',
            name='create_time',
            field=backend.utils.models.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='module',
            name='update_time',
            field=backend.utils.models.CustomDateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='45dcae5a68b7180147d6cccab4fa8cac', max_length=36, verbose_name='UUID'),
        ),
    ]
