# Generated by Django 3.1.7 on 2021-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20211213_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='380f5394bda94d13fc8bac0a803331eb', max_length=36, verbose_name='UUID'),
        ),
    ]
