# Generated by Django 3.1.7 on 2021-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20210829_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='0b0d860e5375d510a180d0953ba7b1aa', max_length=36, verbose_name='UUID'),
        ),
    ]
