# Generated by Django 3.1.7 on 2021-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20210902_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='046ba29399e2341d536761f09d34c147', max_length=36, verbose_name='UUID'),
        ),
    ]
