# Generated by Django 3.1.7 on 2021-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20211213_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='9ef2e64e624e6cf816722c154b571301', max_length=36, verbose_name='UUID'),
        ),
    ]
