# Generated by Django 3.1.7 on 2021-10-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20210902_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='a5629cca607c051228b112d0fef4ac23', max_length=36, verbose_name='UUID'),
        ),
    ]
