# Generated by Django 3.1.7 on 2022-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20211213_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='85f74f15a52d991f17d42b919bbd734b', max_length=36, verbose_name='UUID'),
        ),
    ]
