# Generated by Django 3.1.7 on 2021-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20211009_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='8a1b105a9fdfb8f423f6040f038bf41f', max_length=36, verbose_name='UUID'),
        ),
    ]
