# Generated by Django 3.1.7 on 2021-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20211010_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='e05b0c2cd35f74a1098a319cb3cb7929', max_length=36, verbose_name='UUID'),
        ),
    ]
