# Generated by Django 3.1.7 on 2021-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20211010_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetail',
            name='expectation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='测试步骤'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='step',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='测试步骤'),
        ),
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.CharField(default='ac328b54c0a1b8b27f88cfa4e0852915', max_length=36, verbose_name='UUID'),
        ),
    ]
